#spring.application.name=tp3-instrumentos
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

spring.datasource.url=jdbc:mysql://localhost:3306/tp6magni
spring.datasource.username=root
spring.datasource.password=112233
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

mercadopago.access.token=APP_USR-4263067631955777-051409-b868c36160f7e5cf30c45a44186f44a3-2054898842
url.ngrok=https://b977-190-30-187-11.ngrok-free.app